name: DREAM-env Docker build

on:
  push:
    branches:
      - main

  # Build the Docker container at 00:00 on the first day of every 3 months
  schedule:
    - cron: '0 0 1 */3 *'

name: Build Docker Container

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64  # Multi-platform
          push: true
          no-cache: true
          file: Dockerfiles/Dockerfile
          tags: ghcr.io/dream-gcm/dreamgcm-env:latest
