name: Periodic Docker build

on:
  push:
    branches:
      - main

  # Build the Docker container at 00:00 on the first day of every 3 months
  schedule:
    - cron: '0 0 1 */3 *'

jobs:
  docker:
    name: Build Docker container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build container and push to ghcr
        uses: docker/build-push-action@v5
        with:
          push: true
          no-cache: true
          file: Dockerfiles/Dockerfile.devenv
          tags: ghcr.io/dream-gcm/dreamgcm-env:latest

