jobs:
  docker:
    name: Build Docker container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Log into GitHub Container Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build multi-platform image and push to ghcr
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64  # Adding multiple platforms
          push: true
          no-cache: true
          file: Dockerfiles/Dockerfile.devenv
          tags: ghcr.io/dream-gcm/dreamgcm-env:latest
